# Generated by Django 2.1.7 on 2019-03-29 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateField()),
                ('editedAt', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Evaluator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, choices=[('ADHD', 'Attention-Deficit/Hyperactivity Disorder'), ('ASD', 'Autism Spectrum Disorder'), ('BI1', 'Brain Injury Level 1'), ('BI2', 'Brain Injury Level 2'), ('BI3', 'Brain Injury Level 3'), ('DS', 'Down Syndrome'), ('EDBS', 'Emotional/Behavioral Disorder'), ('GD', 'Global Delay'), ('LD', 'Learning Delay'), ('PDD', 'Pervasive Developmental Disorder')], max_length=4)),
                ('status', models.CharField(max_length=20)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('birthdate', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='evaluation',
            name='evaluatorId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.Evaluator'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='studentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.Student'),
        ),
    ]
