# Generated by Django 2.1.7 on 2019-03-09 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='birthday',
            new_name='birthdate',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
